version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: whack-a-mole-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: whack-a-mole
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - whack-a-mole-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whack-a-mole-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/whack-a-mole?authSource=admin
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - whack-a-mole-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whack-a-mole-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - whack-a-mole-network

volumes:
  mongodb_data:
    driver: local

networks:
  whack-a-mole-network:
    driver: bridge